# Generated by Django 4.0.2 on 2022-02-03 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('description', models.TextField()),
                ('designer', models.CharField(max_length=55)),
                ('year_released', models.IntegerField()),
                ('num_of_players', models.IntegerField()),
                ('estimated_time', models.IntegerField()),
                ('age', models.IntegerField()),
                ('overall_rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GamerRaterAPI.game')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=55)),
                ('gameId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GamerRaterAPI.game')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GamerRaterAPI.user')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=55)),
                ('gameId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GamerRaterAPI.game')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GamerRaterAPI.user')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=55)),
                ('gameId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GamerRaterAPI.game')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GamerRaterAPI.user')),
            ],
        ),
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GamerRaterAPI.category')),
                ('gameId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GamerRaterAPI.game')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GamerRaterAPI.user')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GamerRaterAPI.user'),
        ),
    ]
